# Generated by Django 2.2.6 on 2019-10-19 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
