# Generated by Django 2.2.6 on 2019-11-10 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resetcode',
            name='reset_code',
            field=models.IntegerField(default=788732),
        ),
    ]
