# Generated by Django 2.2.6 on 2019-11-10 01:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_auto_20191110_0113'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ResetCode',
        ),
    ]
