# Generated by Django 2.2.6 on 2019-11-10 01:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_resetcode'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ResetCode',
        ),
    ]
