# Generated by Django 2.2.6 on 2019-10-19 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_auto_20191019_0230'),
    ]

    operations = [
        migrations.AddField(
            model_name='categories',
            name='quantity',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
