# Generated by Django 2.2.6 on 2019-10-19 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0013_auto_20191019_1237'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.IntegerField()),
                ('title', models.CharField(max_length=50)),
                ('category', models.CharField(max_length=50)),
                ('newarrival', models.BooleanField(default=False)),
                ('liked', models.BooleanField(default=False)),
                ('price', models.IntegerField(default=300)),
                ('imgUrl', models.URLField()),
            ],
        ),
        migrations.RenameModel(
            old_name='Product',
            new_name='CartProduct',
        ),
    ]
