# Generated by Django 2.2.6 on 2019-10-21 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0016_products_featured'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartproduct',
            name='_id',
        ),
        migrations.RemoveField(
            model_name='cartproduct',
            name='quantity',
        ),
        migrations.AddField(
            model_name='cartproduct',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cartproduct',
            name='category',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cartproduct',
            name='featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cartproduct',
            name='imgUrl',
            field=models.URLField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cartproduct',
            name='liked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cartproduct',
            name='newarrival',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cartproduct',
            name='price',
            field=models.IntegerField(default=300),
        ),
        migrations.AddField(
            model_name='cartproduct',
            name='product_id',
            field=models.IntegerField(default=99999999),
            preserve_default=False,
        ),
    ]
