# Generated by Django 2.2.6 on 2019-10-27 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0018_cartproduct_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bomba', models.IntegerField()),
            ],
        ),
    ]
