# Generated by Django 2.2.6 on 2019-10-27 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0019_testmodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TestModel',
        ),
    ]
